
/home/huangyh/Desktop/tinybiriscv/vcs/tb/tinybiriscv_soc_tb.v

/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_alu.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_csr_regfile.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_csr.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_decoder.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_decode.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_defs.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_divider.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_exec.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_fetch.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_frontend.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_issue.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_lsu.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_mmu.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_multiplier.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_npc.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_pipe_ctrl.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_regfile.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_trace_sim.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/biriscv_xilinx_2r1w.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/defines.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/full_handshake_rx.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/full_handshake_tx.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/gen_buf.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/gen_dff.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/gpio.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/jtag_dm.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/jtag_driver.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/jtag_top.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/ram.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/rib.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/riscv_core.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/rom.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/spi.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/timer.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/tinybiriscv_soc_top.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/uart_debug.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/uart.v
/home/huangyh/Desktop/tinybiriscv/vcs/rtl/ts1n65lphsa1024x64m4f_210a/VERILOG/ts1n65lphsa1024x64m4f_210a_tt1p2v25c.v
